package Database;

import lombok.Getter;
import lombok.ToString;

@Getter
@ToString
public class MyObject {
    public String id;
    public String name;
    public String email;
    public String password;
    public String avatar;
    public String phone;
    public String dob;
    public String national_id;
    public String nationality;
    public String front_id_card;
    public String back_id_card;
    public String hash;
    public String is_verified;
    public String is_admin;
    public String path;
    public String name_vn;
    public String name_kr;
    public String description_vn;
    public String description_kr;
    public String cards_verified;
    public String province_id;
    public String property_id;
    public String url;
    public String user_id;
    public String property_type_id;
    public String for_sale;
    public String location_id;
    public String price;
    public String created_at;
    public String floor_number;
    public String at_floor;
    public String district_id;
    public String address;
    public String bedrooms;
    public String bathrooms;
    public String area;
    public String hidden;
    public String sold;
    public String property_type_name_vn;
    public String property_type_name_kr;
    public String district_name;
    public String province_name;
    public String floor_numbers;
    public String is_thumb_nail;
    public String amenity_name_vn;
    public String amenity_name_kr;
    public String nearby_location_name_vn;
    public String nearby_location_name_kr;
    public String near_location_id;
    public String amenity_id;
    public String property_type;
    public String numbers;
    public String benefits_vn;
    public String benefits_kr;
    public String number_of_property;
    public String price_per_month;
    public String subscribe_plans_id;
    public String from_date;
    public String to_date;
    public String number_of_comments;
    public String number_of_words_per_cmt;
    public String discount;
    public String price_to_pay;
    public String vnp_BankCode;
    public String vnp_TransactionNo;
    public String vnp_TransactionStatus;
    public String vnp_OrderInfo;
    public String vnp_TxnRef;
    public String vnp_CardType;
    public String vnp_BankTranNo;
    public String create_order_at;
    public String paid_at;
    public String username;
    public String thumbnail;
    public String subscribe_plans_name_vn;
    public String subscribe_plans_name_kr;
    public String hidden_count;
    public String not_hidden_count;
    public String gg_map_api;
    public String title;
    public String content;
    public String like_id;
    public String count_like;
    public String count_comment;
}
